Make rs-bump-version smarter

diff --git a/bin/rs-bump-version b/bin/rs-bump-version
--- a/bin/rs-bump-version
+++ b/bin/rs-bump-version
@@ -22,14 +22,18 @@ if [[ "$project" == rs-unicode ]]; then
     exit 1
 fi
 
-if ! [ -d src ]; then
+if ! [[ -d src ]]; then
     echo "*** Source directory not found"
     exit 1
 fi
 
 cmakefile=src/CMakeLists.txt
-temp=__TEMP__
-header=$(ls src/*/version.hpp)
+header=$(ls src/**/version.hpp)
+
+if ! [[ -f "$header" ]]; then
+    echo "*** Version header not found"
+    exit 1
+fi
 
 version=$(grep -E '^\s+VERSION \d+\.\d+\.\d+' "$cmakefile" \
     | head -n 1 \
@@ -40,8 +44,9 @@ if ! [[ "$version" ]]; then
     exit 1
 fi
 
-namespace=$(grep -E '^namespace ' "$header" \
-    | grep -Eo 'RS\S*')
+namespace=$(grep -E '^namespace ' "$header")
+namespace="${namespace#namespace }"
+namespace="${namespace% \{}"
 
 if ! [[ "$namespace" ]]; then
     echo "*** Namespace not found in version header"
@@ -55,8 +60,8 @@ v3=${version##*.}
 (( ++v3 ))
 echo "Version $v1.$v2.$v3"
 
-sed -E 's!VERSION [0-9]+\.[0-9]+\.[0-9]+!VERSION '"$v1.$v2.$v3"'!' "$cmakefile" > "$temp"
-mv "$temp" "$cmakefile"
+sed -E 's!VERSION [0-9]+\.[0-9]+\.[0-9]+!VERSION '"$v1.$v2.$v3"'!' "$cmakefile" > __TEMP__
+mv __TEMP__ "$cmakefile"
 
 cat << EOF > $header
 // This file is generated by the bump-version script
